# Generated by Django 4.2.2 on 2023-07-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crystal',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='crystal',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
