# Generated by Django 4.2.2 on 2023-07-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_crystal_options_alter_crystal_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiritual', models.CharField(max_length=150)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Uses', to='main_app.crystal')),
            ],
        ),
    ]
