# Generated by Django 4.2.2 on 2023-07-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='spiritual',
            new_name='use',
        ),
    ]
