# Generated by Django 4.2.2 on 2023-07-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_spiritual_use_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='use',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='use',
            name='crystal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='main_app.crystal'),
        ),
    ]
