# Generated by Django 4.2.2 on 2023-07-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_use_use_name_alter_use_crystal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('crystals', models.ManyToManyField(to='main_app.crystal')),
            ],
        ),
    ]
